### ISSUE TITLE
Expand QuickSearch capability on user alias

### ISSUE THREAD

**Issue by iimog** [TBroTeam/TBro#38]
> Hallo Jungs,
> die Quick Search im Tbro sollte vorzugsweise auch - nach dem einloggen - für Aliases funktionieren, >die man selbst in eigenen Carts erstellt hat!
> Wäre prima 

User alias should be also searched when using the quick search.
Should the user description be searched for as well?

**Comment by dbecker64** [comment]
of course !!

**Comment by iimog** [comment]
I just pushed this to the carnivorom instance. @dbecker64 please verify that it works for you.

Current functionality of Quicksearch is:
- Autocompletion is triggered after entry of at least 3 characters and a delay of 500ms
- User alias / User description is searched for this substring (all hits are returned)
- This also works on the default cart if the user is not logged in
- The database is searched for name, alias and description with a limit of 10 hits each
- All searches are case sensitive (tests with case insensitive searches had dramatically worse performance)
- Hits in user annotations are always on top other hits appear in no particular order (might also differ on consecutive searches of the same term)

@fbemm please also approve the current functionality

**Comment by fbemm** [comment]
Is it possible to show the subordinate unigene for an alias hit? otherwise the list of different AMT's is a bit useless. does the same search procedure also work in the name search?

**Comment by iimog** [comment]
@fbemm It is possible to display the unigene/isoform name alongside the string. However expecially for the user alias / description this requires calling an additional webservice. It will increase loading time of the autocompletion. Further it would not make sense to add an additional column to the result table as that column would not be required if the hit is on the name (eg searching for "comp").
Would it be ok to add the hit in parentheses like that (hypothetical search for 123):

```
user alias       | comp2345 (bla123)
user description | comp567 (bla bla bla blub 123 bla bla)
isoform          | comp1234_1
isoform          | comp1234_2
isoform          | comp1235_1
isoform          | comp1236_1
unigene          | comp1234
unigene          | comp1235
unigene          | comp1236
description      | comp567 (bla blub 01234 bla blub)
```

**Comment by iimog** [comment]
@fbemm The name search uses a different procedure searching only for database name and alias (description is not included, neither are user alias and annotation). Instead it is possible to extend the search to related isoforms/unigenes. If a different functionality is required please open a separate issue.

**Comment by dbecker64** [comment]
Quick search now works fine - especially on user-defined carts (following login). In order to assess the significance of retrieved hits it would be necessary to have additional information about the associated unigene/isoform. Working with brackets is fine.

**Comment by iimog** [comment]
New version including feature names deployed on http://tbro.carnivorom.com/
Please check it out @dbecker64 @fbemm and tell me if this issue is resolved.

**Comment by dbecker64** [comment]
solved!!
