### ISSUE TITLE
Upload files when "searching by name"

### ISSUE THREAD

**Issue by nterhoeven** [TBroTeam/TBro#41]
When using the "Search by Name" functionality, I would like to have the possibility to upload a file containing the list of IDs instead of typing them into the search field.

Could you implement this functionality?

**Comment by fbemm** [comment]
I don't see why copy paste is so hard to use here. The limit that we currently set would be applied to both methods (500 at the moment?). Batch request can also be done directly using the web services.

**Comment by nterhoeven** [comment]
It is not hard to use, but file upload would be much more convenient.

Example:
I am doing some analyses which result in a list of 100 isoform IDs. Typically these would be stored in a list with one ID per line. Now I want to check their expression levels in Tbro. The most convenient way for me to do this would be to upload the file directly.
Of course, I can copy paste the IDs, but therefore I would have to open the file, copy the lines while scrolling down (most screens cannot display all lines at once), switch to my browser and paste the data. 
A file-upload functionality would make this process easier.

**Comment by fbemm** [comment]
You can do that directly on the command line using the TBro API respectively the proper webservice.
