### ISSUE TITLE
Download of complete Dataset

### ISSUE THREAD

**Issue by nterhoeven** [TBroTeam/TBro#42]
It would be nice to have an easy way to download the complete dataset. Currently I can do this by selecting "data"->"expression counts" and then extract the data with all filters "off". 

I would like to have a "download all" page where I can select different `.tar.gz` archives containing for example the Isoform sequences or the expression counts

**Comment by fbemm** [comment]
Expression counts can be exported already. I don't see the necessity to prepackage the data into compressed archives. We would need to store them locally or in the database. For sequences this feature could be useful. Plz open a new issues for that.

**Comment by fbemm** [comment]
See #21
