### ISSUE TITLE
Linking out to SmartBLAST

### ISSUE THREAD

**Issue by 000generic** [TBroTeam/TBro#52]
Hi!

I'm exploring TBro more and more as I implement more of its functionality - and think its great! 
 In working with it, I'm coming up with different ideas for new features, and thought this one might be relatively easy and useful.

SmartBLAST is a new(-ish) feature at NCBI that blasts queries against a set of 27 (and hopefully growing number of) complete high quality genomes representing major branches across the Tree of Life - and outputs top hits of the top 5 species in a tree with conserved domains identified.  I feel like it provides a really useful way of assessing top blast hits of transcript in a phylogenetic context - with the complete genomes strengthening a given annotation call.  

https://blast.ncbi.nlm.nih.gov/smartblast/smartBlast.cgi?CMD=Web&PAGE_TYPE=BlastDocs#searchSets

Currently, I often go from TBro to NCBI BLAST via the TBro button that is provide.  And after blasting at NCBI nr, I typically go on to SmartBLAST - but I am often most interested in seeing the SmartBLAST results.  So, I thought it might be a useful enhancement to Tbro to include a button to go directly NCBI SmartBlast (if such a feature is possible) - to speed things up.

Good luck with all your great work with TBro!

**Comment by iimog** [comment]
Thanks for the suggestion. This is indeed a useful feature. Furthermore it should not be difficult to implement as the smartblast page allows a `QUERY` parameter, try:
https://blast.ncbi.nlm.nih.gov/smartblast/smartBlast.cgi?QUERY=%3Etest%0AMTEST

A link like this can be generated from the Isoform page of TBro dynamically with the current protein sequence without any problem. I'm currently at a conference but I will add this feature early next week.

**Comment by 000generic** [comment]
Awesome!

**Comment by iimog** [comment]
This feature is now available in the `smart_blast` branch. If you want to try it you can clone the `TBro` repository somewhere inside your docker container, checkout the `smart_blast` branch. Copy `/home/tbro/build.properties` into this repository. Run `source ~/.bash_profile` and then `phing web-install`. After that the button should be visible in the web interface. I will add some more features before I merge back into the `master` branch.
