### ISSUE TITLE
Creation of large carts fails sometimes

### ISSUE THREAD

**Issue by iimog** [TBroTeam/TBro#54]
The cart limit can be configured in the `config.php` file. However on one instance I experienced problems when creating large carts (~2000 items) even though the cart limit was 10000.

Minimal example:
 - do a differential expression search with parameters such that ~2000 items are returned
 - click "Select" > "All"
 - click "Store" > "new"

Behaviour:
 - The cart is created and shows up on the right side with correct number of items
 - After some time (or a refresh) the cart is still there but empty

It seems that the `sync` that adds the items (different `sync` than that which creates the cart) either times out or runs out of memory and so never finishes. Thus with the next sync the empty cart is returned.

**Comment by iimog** [comment]
After some investigation it seems that the php limit on variables causes this error.
In the `/etc/php5/apache2/php.ini` the default is:
```
max_input_vars = 1000
```
This way all requests with more than 1000 variables are automatically dropped.
This variable has to be adjusted according to the setting in the `config.php`
I will add a custom `php.ini` to the docker container to avoid this problem in the future.

**Comment by phryneas** [comment]
instead of POSTing an array structure, it could also be json_serialized in the javascript before sending as well - then it would be only one POST variable.

**Comment by greatfireball** [comment]
I think a single variable would be fine... See @phryneas suggestion.
Is there a size limit (of a single serialized variable) which might cause trouble?

**Comment by phryneas** [comment]
php's post_max_size - but that would apply for the sum of a thousand variables as well

**Comment by greatfireball** [comment]
I just wanted to avoid further issues... In that case it might be possible to check the size of the serialized stream and compare it to that value? Thus the user can be informed, that the cart is to large and he/she needs to reduce the size?

**Comment by iimog** [comment]
Thanks for the good suggestions. I wanted to avoid the cart system as much as possible :smile: but I agree that this is a better way to do it. I'll have a look at it.

**Comment by phryneas** [comment]
POST size should in this context never be a problem, as we're talking ASCII representation of 32-bit-integers here.
So we have roughly `count(added items)*(charcount("2147483647")+3)`  bytes - that will hardly ever exceed kilobytes.
