### ISSUE TITLE
BLAST database error

### ISSUE THREAD

**Issue by 000generic** [TBroTeam/TBro#56]
When I **Search by Homology**, I'm getting the following error after repeat installations from the ground up and using a protocol that had been working a month ago for installing TBro in Amazon Lightsail:

**These errors occurred:
BLAST Database error: No alias or index file found for protein database [/tmp/queue-worker//squid-SRA-Yale-max-diversity-AA.52acbc6e906029a04ea3ac850bb75674/squid-SRA-Yale-max-diversity-AA] in search path [/tmp/queue-worker::]**

It seems like everything works and installs correctly, so I'm not sure where the problem is.  Any ideas or suggestions would be great.

Thank-you,
Eric

**Comment by iimog** [comment]
Hi Eric,

sorry to hear that there are new problems popping up. The good thing is that this error message indicates that the queue database and the worker can communicate. However there is either a problem with the prepared blast database zip file or in the communication between the blast worker and the worker ftp. In order to track down this issue could you please look what the content of `/tmp/queue-worker/` (and subdirectories) is on your blast worker `TBro_Worker_official`.

If the zip file is not there please try to download it with `wget` using the url you have stored in the database.

What is the content of the directory? Have you been able to download the file with `wget`?

**Comment by 000generic** [comment]
It turned out to be an Eric Error - not a new problem in Tbro/Docker/Amazon.  Basically, my name for the database wasn't a match to the name used for the zip file.  Sorry for the trouble!

Btw, I have a protocol for setting up Tbro in Docker in Amazon - and including password protection:

https://benchling.com/s/prt-DHSo7HeddC5zM0x7x1Y4

I need to add details on setting up Amazon Lightsail - and details on exactly what files should be prepared ahead of time to have it fully encapsulate things start to finish - but the basic steps are all there - and it can be set up by copy and paste - and replacing terms in red with user-specific file names and details.

**Comment by iimog** [comment]
Awesome. I had a look at your protocol and it is very good. I'd like to link to this protocol form the official documentation if that is ok for you (and if it stays at this location). Once you have finished the guide, I'd also be more than happy to merge a pull request into the official documentation.

**Comment by 000generic** [comment]
Sure!  The protocol's location will be stable but the contents may change with improvements and details.  I'll put in a pull request once I finish it - most likely in the second half of August.

**Comment by iimog** [comment]
Perfect, thanks!

**Comment by 000generic** [comment]
Here is a final template for creating TBro in the Amazon cloud:  

https://benchling.com/s/prt-DHSo7HeddC5zM0x7x1Y4

or as a pdf

[PROTOCOL TBro Amazon Lightsail Template 1.0 - Edsinger July 21 2017.pdf](https://github.com/TBroTeam/TBro/files/1167706/PROTOCOL.TBro.Amazon.Lightsail.Template.1.0.-.Edsinger.July.21.2017.pdf)

I've skipped details on how to prepare the materials required by TBro - and have not fleshed out all the TBro features, like comparisons of expression.  However, the protocol does allow exploration of an annotated transcriptome by BLAST, which I think is a common minimal use case for a de novo transcriptome.

I can add in the other TBro features to the protocol this fall.

To do a pull request to add the current protocol to the official documentation, I'm a little unsure on what to do.  Would I:

1)  Fork TBro
2) Modify a documentation file
3) Submit a pull request

If so, where can I find the documentation file?  I looked around but didn't see anything.

Thanks!

**Comment by iimog** [comment]
Hi @000generic thats fantastic.
You are right. The workflow consists of those three steps. Except the documentation of TBro lives in a separate repository: https://github.com/TBroTeam/Tutorial
So you have to fork that one. The relevant file is then `docs/guides.rst`
We use [reStructuredText](http://www.sphinx-doc.org/en/stable/rest.html) for formatting.
If you need any help do not hesitate to ask.
