### ISSUE TITLE
carts cannot be filled

### ISSUE THREAD

**Issue by nterhoeven** [TBroTeam/TBro#59]
Sometimes carts can't be filled with items. The items get lost during the sync.

from the apache error log:

```
Maximum execution time of 30 seconds exceeded in /share/tbro/TranscriptDB/webservices/cart/Sync.php on line 180
```
Line 180 of this file:

```
$ids_context = array_intersect($parms['ids'], $results['results']);
```

**Comment by iimog** [comment]
Hi @nterhoeven thanks for reporting this.
I had a look at it and it seems to happen for some organism/release combinations and not for others.
Interestingly the number of features in the release that works fine is even larger than that in the release that does not work.
Increasing `max_execution_time` to 300 is enough to make it work but the full five minutes are used.
I'll have to dig a little deeper.

**Comment by nterhoeven** [comment]
@iimog and me took a closer look at this Problem. 

The line in question is a sanity check to prevent that IDs from wrong Organism-release combinations are added to a cart. When the datasets get larger (several hundred thousand transcripts) the comparison of the two arrays is very slow.

We decided for a temporary solution
The check is skipped by changing the following steps:
- outcomment line 174 (`$results = ($service->execute(array('species' => $cont[0], 'release' => $cont[1])));`)
- change line 180 to `$ids_context = $parms['ids'];`

**We should still find a better solution here**, but until then, TBro is at least useable.
